version: '3'

services:
  proxy:
    image: traefik:latest
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG --accesslogsfile=/dev/stdout
    ports:
      - '${HOST_MACHINE_UNSECURE_HOST_PORT}:80'
      - '${HOST_MACHINE_SECURE_HOST_PORT}:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./acme.json:/acme.json
    networks:
      - frontend
    labels:
      - 'traefik.backend=proxy'
      - 'traefik.frontend.rule=Host:${DOMAIN};PathPrefixStrip:/traefik/'
      - 'traefik.docker.network=frontend'
      - 'traefik.port=8080'

  php:
    image: hub.t-me.pp.ua/wi1w/webserver:7-1-opencart
    command: bash -c 'sh /var/www/html/php-init.sh && sh /migrate.sh && . /etc/apache2/envvars; /usr/sbin/apache2 -DFOREGROUND' 
    volumes:
      - ./migrate.sh:/migrate.sh
      - ./www:/var/www/html
      - ./php-init.sh:/var/www/html/php-init.sh
      - ./logs/apache2:/var/log/apache2
      - ./config/vhosts/default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - mariadb
    depends_on:
      - mariadb
    networks:
      - backend
      - frontend
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DOMAIN: ${DOMAIN}
    labels:
      - 'traefik.backend=goodmarket'
      - 'traefik.frontend.rule=Host:${DOMAIN},www.${DOMAIN}'
      - 'traefik.docker.network=frontend'
      - 'traefik.port=80'
      - 'traefik.frontend.redirect.permanent=true'
      - "traefik.frontend.redirect.regex=^https://www.${DOMAIN}/(.*)$$"
      - "traefik.frontend.redirect.replacement=https://${DOMAIN}/$$1"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  mariadb:
    image: mariadb:10.3
    command: bash -c "chown -R mysql:mysql /var/log/mysql && exec /docker-entrypoint.sh mysqld --log-error=/var/log/mysql/err.log --general-log=1 --general-log-file=/var/log/mysql/general-log.log --character-set-server=utf8 --collation-server=utf8_general_ci"
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./db/bcp.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - backend
    labels:
      - 'traefik.enable=false'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - frontend
      - backend
    volumes: 
      - /sessions
    labels:
      - "traefik.backend=goodmarket_phpmadm"
      - "traefik.frontend.rule=Host:${DOMAIN};PathPrefixStrip:/madmin/"
      - "traefik.docker.network=frontend"
      - "traefik.port=80"
      - 'traefik.frontend.auth.basic=${AUTH}'

networks:
  frontend:
    external: true
  backend:
    external: false
