<?php
return [
    '1' => [
        'page_id' => 1,
        'h1' => 'header_ru',
        'title' => 'title',
        'keywords' => 'keywords',
        'description' => 'description',
        'seo_text' => '<p><span class="label-red">Label</span></p>',
        'language' => 'ru',
        'parent_id' => null,
        'alias' => 'category',
    ],
    '2' => [
        'page_id' => 1,
        'h1' => 'header_eng',
        'title' => 'title',
        'keywords' => 'keywords',
        'description' => 'description',
        'seo_text' => '<p><span class="label-red">Label</span></p>',
        'language' => 'eng',
        'parent_id' => null,
        'alias' => 'category',
    ],
    '3' => [
        'page_id' => 2,
        'h1' => 'header_ru',
        'title' => 'title',
        'keywords' => 'keywords',
        'description' => 'description',
        'seo_text' => '<p><span class="label-red">Label</span></p>',
        'language' => 'ru',
        'parent_id' => null,
        'alias' => 'category',
    ],
    '4' => [
        'page_id' => 2,
        'h1' => 'header_eng',
        'title' => 'title',
        'keywords' => 'keywords',
        'description' => 'description',
        'seo_text' => '<p><span class="label-red">Label</span></p>',
        'language' => 'eng',
        'parent_id' => null,
        'alias' => 'category',
    ],
];
